### PR TITLE
Update to Az module

### PR DESCRIPTION
**Pull request by akhilthomas011**

### CODE REVIEW

**Comment by akhilthomas011** [comment]
@AutomationProductTeam - Not sure if this is the right way to update a migrated script from Technet Gallery. Please let me know if any changes are to be made. Thanks!

**Comment by akhilthomas011** [comment]
@Jinesh12

**Comment by jineshcodes** [comment]
> @AutomationProductTeam - Not sure if this is the right way to update a migrated script from Technet Gallery. Please let me know if any changes are to be made. Thanks!

There are 2 ways to go about it:
1) Creating a PR here, may need for someone from the Product team to approve.
2) Creating a new repo with appropriate tags and details and the repo will start showing up on the Azure portal. This will be immediate but the side-effect would be that now users will be seeing 2 runbooks on the gallery with a similar title. (To mitigate this you can reach out to us and we can remove the tag from this source runbook) 

This Blog should help in understanding the process: https://techcommunity.microsoft.com/t5/azure-governance-and-management/azure-automation-runbooks-moving-to-github/ba-p/2039337

**Review by jineshcodes — APPROVED** [review]
Approving as the changes are made by the original Author of the runbook.

**Comment by akhilthomas011** [comment]
@Jinesh12  - In that case, I guess it's good to create a new repo independently, so that its easy to make changes to it. Do we need to add metadata file in it? The document you send doesn't tell that.
Here's the new repo: https://github.com/akhilthomas011/Auto-Resize-Azure-VM-With-Tags
If this is good enough, please remove the migrated repo.

**Pull request merged**
